-- Split the Page column of the flat train data

DROP TABLE IF EXISTS train_flat_split;

CREATE TABLE train_flat_split AS (
  SELECT "Page" AS page,
         reverse(split_part(reverse("Page"), '_', 3)) AS project,
         reverse(split_part(reverse("Page"), '_', 2)) AS access,
         reverse(split_part(reverse("Page"), '_', 1)) AS agent,

         "Date" AS date, "Visits" AS visits
    FROM train_flat
);


-- Table of features (visits_lag#, project, access, and agent) and response value (visits)

DROP TABLE IF EXISTS xy;

CREATE TABLE xy AS (
  SELECT page, project, access, agent, date, visits,
         lag(visits, 9) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag9,
         lag(visits, 10) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag10,
         lag(visits, 11) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag11,
         lag(visits, 12) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag12,
         lag(visits, 13) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag13,
         lag(visits, 14) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag14,
         lag(visits, 15) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag15,
         lag(visits, 16) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag16,
         lag(visits, 17) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag17,
         lag(visits, 18) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag18,
         lag(visits, 19) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag19,
         lag(visits, 20) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag20,
         lag(visits, 21) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag21,
         lag(visits, 22) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag22,
         lag(visits, 23) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag23,
         lag(visits, 24) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag24,
         lag(visits, 25) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag25,
         lag(visits, 26) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag26,
         lag(visits, 27) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag27,
         lag(visits, 28) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag28,
         lag(visits, 29) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag29,
         lag(visits, 30) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag30,
         lag(visits, 31) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag31,
         lag(visits, 32) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag32,
         lag(visits, 33) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag33,
         lag(visits, 34) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag34,
         lag(visits, 35) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag35,
         lag(visits, 36) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag36,
         lag(visits, 37) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag37,
         lag(visits, 38) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag38,
         lag(visits, 39) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag39,
         lag(visits, 40) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag40,
         lag(visits, 41) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag41,
         lag(visits, 42) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag42,
         lag(visits, 43) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag43,
         lag(visits, 44) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag44,
         lag(visits, 45) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag45,
         lag(visits, 46) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag46,
         lag(visits, 47) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag47,
         lag(visits, 48) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag48,
         lag(visits, 49) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag49,
         lag(visits, 50) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag50,
         lag(visits, 51) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag51,
         lag(visits, 52) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag52,
         lag(visits, 53) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag53,
         lag(visits, 54) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag54,
         lag(visits, 55) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag55,
         lag(visits, 56) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag56,
         lag(visits, 57) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag57,
         lag(visits, 58) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag58,
         lag(visits, 59) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag59,
         lag(visits, 60) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag60,
         lag(visits, 61) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag61,
         lag(visits, 62) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag62,
         lag(visits, 63) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag63,
         lag(visits, 64) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag64,
         lag(visits, 65) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag65,
         lag(visits, 66) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag66,
         lag(visits, 67) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag67,
         lag(visits, 68) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag68,
         lag(visits, 69) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag69,
         lag(visits, 70) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag70,
         lag(visits, 71) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag71,
         lag(visits, 72) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag72,
         lag(visits, 73) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag73,
         lag(visits, 74) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag74,
         lag(visits, 75) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag75,
         lag(visits, 76) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag76,
         lag(visits, 77) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag77,
         lag(visits, 78) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag78,
         lag(visits, 79) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag79,
         lag(visits, 80) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag80,
         lag(visits, 81) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag81,
         lag(visits, 82) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag82,
         lag(visits, 83) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag83,
         lag(visits, 84) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag84,
         lag(visits, 85) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag85,
         lag(visits, 86) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag86,
         lag(visits, 87) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag87,
         lag(visits, 88) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag88,
         lag(visits, 89) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag89,
         lag(visits, 90) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag90,
         lag(visits, 91) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag91,
         lag(visits, 92) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag92,
         lag(visits, 93) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag93,
         lag(visits, 94) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag94,
         lag(visits, 95) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag95,
         lag(visits, 96) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag96,
         lag(visits, 97) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag97,
         lag(visits, 98) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag98,
         lag(visits, 99) OVER (PARTITION BY page ORDER BY date ASC) AS visits_lag99
    FROM train_flat_split
   ORDER BY page ASC, "date" ASC
);
